/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.ljn.jp.test;

import io.ljn.jp.test.generator.GenerateTests;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        GenerateTests classUnderTest = new GenerateTests();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
