/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.ljn.jp.test.generator;

public class GenerateTests {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new GenerateTests().getGreeting());
    }
}
